#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails rails new . --force --database=mysql --skip-bundle --skip-git --skip-test --api && bundle update

cp -f template/database.yml config/database.yml

docker-compose run --rm rails bundle exec spring binstub --all #bin/spring が新規追加され、bin/rails, bin/rake にspringをloadするコードが追加される。
